title: Pandora's Code
description: > 
  I like exploring the intersection of deep learning theory and real-world applications

theme: minima
author: Zehra Korkusuz
email: wzehrakorkusuz@gmail.com

base_url: /
repository: zehrakorkusuz/zehrakorkusuz.github.io

# Minima social links
github_username: zehrakorkusuz
kaggle_username: zehrakorkusuz
twitter_username: wzehrakorkusuz
# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/about.md
  - _pages/archive.md
  - _pages/projects.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
