description: Zehra Korkusuz
author: "Zehra Korkusuz"

theme: minima

base_url: /gh-pages-minima-starter
repository: jsanz/gh-pages-minima-starter

# Minima social links
github_username: zehrakorkusuz
kaggle_username: zehrakorkusuz
# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md
  - _pages/projects.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
